name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.release_url }}
    steps:
      - name: Create release
        id: create_release
        uses: SamoKopecky/.github/.github/actions/create-time-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    needs: create_release
    strategy:
      matrix:
        file: [code-presentation, paper-presentation]
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish
      uses: SamoKopecky/.github/.github/actions/latex-to-release-pdf@main
      with:
        release_url: ${{ needs.create_release.outputs.release_url }}
        file_name: ${{ matrix.file }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.event.client_payload.repository }}